### ISSUE TITLE
Skip pattern to disable tracing

### ISSUE THREAD

**Issue by pilhuhn** [eclipse/microprofile-opentracing#16]
MP Config should be used to enable/disable feature e.g. by uri
similarly filtering of endpoints that should not be traced (e.g. /health)

**Comment by Steve-Fontes** [comment]
I'd like to defer this feature to microprofile-opentracing 1.1 in the interests of delivering the function proposed so far in microprofile 1.3.

**Comment by Steve-Fontes** [comment]
An implementation could be to provide an ordered list of exclude and include filters.

We had implemented this using open-liberty specific config, because I did not think it would be something we wanted to add to the Spec.
Since we have decided it is something that should be standard across microprofile implementations. I disabled the filtering function in the open-liberty code. We'll eventually use the standard config mechanism we decide on here.

Liberty config is xml file based, and we defined filters like:

<opentracing>
   <excludeSpans pattern="URI" type="INCOMING|OUTGOING|BOTH" ignoreCase="true|false" regex="true|false" />
   <includeSpans pattern="URI" type="INCOMING|OUTGOING|BOTH" ignoreCase="true|false" regex="true|false" />
</opentracing>

See javadoc at the top of https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/filters/SpanFilter.java

The implementation tests each request against the exclude filters, then the include filters. 

I'm not saying that is what we should pattern the spec after, but it is a starting point for discussion.

**Comment by pavolloffay** [comment]
@fmhwong the main question still remains: Can be everything expressed with only exclude pattern?

For example I would like to exclude `/foo/bar/*` but include `/foo/bar/baz` I could write exclude pattern = `/foo/bar/(?!include).*`.

If we cannot find a use case when include pattern is really needed then I am -1 for it.

**Comment by fmhwong** [comment]
@pavolloffay The only concern from Steve was about performance in regex.  In his proposal, he allows string match (without using regex).  Having exclude and include will be useful in that case.

**Comment by pavolloffay** [comment]
> * If regex is true, pattern is compiled into a {@see java.util.regex.Pattern} and
> * the URI is matched interpreting the pattern as a regular expression

https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/filters/SpanFilter.java#L48 

It is complied to pattern anyways. To avoid regex we would have to consume a list of URL strings and do equals but it's not user friendly.

**Comment by pavolloffay** [comment]
On the weekly meeting we decided to go only with skip pattern as a regex. It will be configured in mp-config style e.g. `mp.opentracing.skip-pattern="/health/*|/metrics/*"`.

We could also think of a default value - exclude health, favicon, metrics, some static assets.

**Comment by fmhwong** [comment]
@pavolloffay Is the proposal just to exclude the tracing solely according to the URL?  What if I have a microservice A `/serviceA` that will call service B `/serviceB` and C `/serviceC`, and I have set the exclude filter to  `/serviceA`.  Will B and C still got traced?

**Comment by pavolloffay** [comment]
Yes the client invocations of `/serviceB` and  `/serviceC` will still by traced

**Comment by fmhwong** [comment]
In this case, what is the parent of spans for service B and C?

**Comment by pavolloffay** [comment]
There would not be any part. These two requests would start two new traces unless user created an active span.

**Comment by fmhwong** [comment]
Not exactly.  Just thinking if we skip tracing A and we still trace B and C.  That will create 2 orphan spans.  Not sure if this is what people are expecting.

**Comment by pavolloffay** [comment]
I think that is expected that outbound requests are configured/traced separately. If there is a need we could have a separate skip pattern for outbound requests. Having one skip pattern can be very tricky to implement. I think we even cannot get the original request path if the client is used on a different thread or its part of batch processing.

**Comment by pavolloffay** [comment]
We should decide what to do if `@Traced(true)` is used on an endpoint which is skipped. Should the endpoint be traced or not?  

Note that by default everything is traced. 

* if the annotation takes precedence over skip-pattern then it assures that the endpoint will be always traced. It also simplifies enabling certain endpoints from not being traced e.g. include /foo/bar when /foo/.* is excluded.  
* If the skip pattern takes precedence it makes it possible to fully control what is traced via conf properties.

**Comment by pavolloffay** [comment]
@pilhuhn @kenfinnigan @objectiser do you have any preference in ^^ https://github.com/eclipse/microprofile-opentracing/issues/16#issuecomment-417614075?

**Comment by kenfinnigan** [comment]
I think it makes sense for the config property to be able to override an annotation, otherwise you're not really providing the ability to skip anything
