### ISSUE TITLE
Upgrade to OpenTracing 0.33.0

### ISSUE THREAD

**Issue by pavolloffay** [eclipse/microprofile-opentracing#178]
Supersedes https://github.com/eclipse/microprofile-opentracing/issues/150

Based on the discussion in https://groups.google.com/d/msg/microprofile/unYFj9EpTgM/3pu7yppyAwAJ we have decided to directly bump version from 0.31.0 to 0.33.0 (skip 0.32.0) and release it in MicroProfile-OpenTracing 2.0.

The MP-OT 2.0 then will be a standalone spec (removed from MicroProfile umbrella, https://groups.google.com/d/msg/microprofile/unYFj9EpTgM/UMRjGy8rBAAJ) or included in summer release 4.0.

**Comment by rmannibucau** [comment]
Hi @pavolloffay , shouldnt MP-OT 2 just move to opentelemetry which superseeds opentracing API?

**Comment by pavolloffay** [comment]
Please follow the discussion on the mailing list. OpenTelemetry will be likely a new spec.

**Comment by rmannibucau** [comment]
Yep but then what is the point to continue opentracing? Just adds more noise to MP and gives an even more obvious "sandbox" image which is not good IMHO.

**Comment by pavolloffay** [comment]
Btw. there is no stable release of OpenTelemetry at the moment. Not sure if there will be one before June and even though we will have to build a new spec/integration for it which will take some time.

So rather than staying on old OT API version causing incompatibility with other instrumentations and unmaintained Tracer implementations we should upgrade anyway.

Please continue the discussion on the mailing list.

**Comment by rmannibucau** [comment]
0.2.0 is already available (https://github.com/open-telemetry/opentelemetry-java/releases)
Tracer impl can be part of MP stack (it is the case for geronimo implementation for ex) so maintenance point is purely a vendor choice.
Incompatibility has not been an issue for a year so guess 6 more months is not an issue.
This is why I think a new major immediately superseeded by the merge of opentracing and metrics (which is a good move) is a bad choice and the 0.33 upgrade shouldn't happen since it will break end users, require work, then enforce them to change all their API.

**Comment by pavolloffay** [comment]
> 0.2.0 is not a stable release.

It does not seem like a stable release. See the semver semantics. We don't want to repeat the same problems we had with going with OpenTracing.

> Tracer impl can be part of MP stack

Yes, it Otel SDK will be probably part of the MP spec.

> 0.33 upgrade shouldn't happen since it will break end users, require work, then enforce them to change all their API.

That is why it might go to breaking change release or be taken away from the umbrella spec

**Comment by kenfinnigan** [comment]
It's highly likely that OpenTracing 2.0 will be released, but also removed from the MP Platform umbrella for MP 4.0 to allow easier inclusion of OpenTelemetry when it's ready
